# Generated by Django 5.2 on 2025-06-07 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0003_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatgroup',
            name='personal_chat',
            field=models.BooleanField(default=False),
        ),
    ]
