# Generated by Django 5.1.4 on 2025-06-10 17:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0004_chatgroup_personal_chat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='views',
            field=models.ManyToManyField(related_name='viewed_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
